// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxxcobddlerchtokpvyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4eGNvYmRkbGVyY2h0b2twdnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODE5NzgsImV4cCI6MjA3MjQ1Nzk3OH0.g6Cvwdk9P4nSPd6v-J6KKxLIHa70NEaEC2pPpGamGHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});